;;; -*- lisp-data -*-
(("/home/george/dotfiles/") ("/home/george/dev/aoc25/")
 ("/home/george/dev/pakas-capital/")
 ("/home/george/dev/rust/spotiver/")
 ("/home/george/Downloads/sqlite/") ("/home/george/notes/")
 ("/home/george/dev/pakas-capital/py-clob-client/")
 ("/home/george/Next/mwa_airflow/")
 ("/home/george/Next/marketing_webanalytics/")
 ("/home/george/Next/marketingdata_platform/")
 ("/home/george/Next/ariel/ariel/") ("/home/george/Next/vigenair/")
 ("/home/george/Next/firebasereiss-dmk-azure-dev/")
 ("/home/george/cv/") ("/home/george/Next/marketing-webanalytics/")
 ("/home/george/Next/gcp-dataform-test/")
 ("/home/george/dev/banking-analysis/")
 ("/home/george/dev/vortexa-land-storage-assignment/")
 ("/home/george/dev/cholec_analyzer/")
 ("/home/george/dev/coding-interview-990mwl/")
 ("/home/george/dev/rvu-pairing-interview/")
 ("/home/george/dev/rust/tkup/") ("/home/george/dev/revzak/")
 ("/home/george/Next/ga-entities-reiss/")
 ("/home/george/dev/rust/genealogy/") ("/home/george/dev/rust/aoc23/")
 ("/home/george/dev/rust/genp/")
 ("/home/george/dev/rust/scrolling-display/")
 ("/home/george/dev/rust/pandemic_simulation/")
 ("/home/george/dev/rust/ml/") ("/home/george/Next/ga-entities/")
 ("/home/george/dev/rust/testing/")
 ("/home/george/dev/rust/rust-tut/") ("/home/george/dev/qtile/")
 ("/home/george/dev/rust/minicel/") ("/home/george/dev/rust/aoc21/")
 ("/home/george/dev/ded/") ("/home/george/dev/spare-car-parts/")
 ("/home/george/dev/foobar/") ("/home/george/dev/rust/aoc22/")
 ("/home/george/dev/rust/clocktui/")
 ("/home/george/dev/rust/colour-stats/")
 ("/home/george/dev/rust/kmeans-colors/")
 ("/home/george/dev/rust/life/") ("/home/george/dev/rust/nannou/")
 ("/home/george/dev/rust/nannou-tut/"))
