;;; -*- lisp-data -*-
(("/home/neeto/dotfiles/")
 ("/home/neeto/Next/marketing-webanalytics/") ("/home/neeto/notes/")
 ("/home/neeto/dev/barser/")
 ("/home/neeto/dev/flutter/google_maps_flutter/google_maps_flutter_android/")
 ("/home/neeto/dev/flutter/gmaps_example/")
 ("/home/neeto/dev/flutter/packages/")
 ("/home/neeto/dev/flutter/cinemap/")
 ("/home/neeto/dev/flutter/basics/")
 ("/home/neeto/dev/flutter/basics")
 ("/home/neeto/dev/rust/kmeans-colors/")
 ("/home/neeto/dev/rust/spotiver/") ("/home/neeto/dev/rust/tkup/")
 ("/home/neeto/cv/") ("/home/neeto/Next/marketingdata_platform/")
 ("/home/neeto/dev/cinemap/crux/shared/")
 ("/home/neeto/shared/marketing-webanalytics/")
 ("/home/neeto/dev/rust/genealogy/") ("/home/neeto/dev/rust/aoc21/")
 ("/home/neeto/dev/rust/aoc23/")
 ("/home/neeto/Next/marketingdata_ETL/")
 ("/home/neeto/dev/rust/aoc23/")
 ("/home/neeto/Next/marketingdata_ETL/")
 ("/home/neeto/dev/rust/aoc21/") ("/home/neeto/dev/rust/aoc22/")
 ("/home/neeto/dev/spare-car-parts/") ("/home/neeto/cv/")
 ("/home/neeto/dev/rust/spotiver/")
 ("/home/neeto/shared/ga-entities/") ("/home/neeto/dev/rust/genp/")
 ("/home/neeto/dev/rust/testing/") ("/home/neeto/dev/rust/rustlings/")
 ("/home/neeto/dev/rust/colour-stats/") ("/home/neeto/dev/rust/life/")
 ("/home/neeto/dev/qtile/") ("/home/neeto/dev/rust/minicel/")
 ("/home/neeto/dev/ded/") ("/home/neeto/dev/foobar/")
 ("/home/neeto/dev/rust/clocktui/") ("/home/neeto/dev/rust/nannou/")
 ("/home/neeto/dev/rust/nannou-tut/")
 ("/home/neeto/dev/rust/rust-tut/"))
