#!/bin/sh

SPEAKERS_ID="pebble"
HEADPHONES_ID="hyperx"

if [ -z $(pactl get-default-sink | grep -i $HEADPHONES_ID) ]; then
    sink=$(pacmd list-sinks | grep -m 1 -B 1 -i $HEADPHONES_ID)
    new_sink="Headphones"
else
    sink=$(pacmd list-sinks | grep -m 1 -B 1 -i $SPEAKERS_ID)
    new_sink="Speakers"
fi

pacmd set-default-sink $(echo "$sink" | sed -En 's/^ +index: ([0-9]+).*/\1/p')
echo $new_sink
